// flow-typed signature: d7eb86a6e19208a353c9c21d6647448c
// flow-typed version: <<STUB>>/babel-plugin-shed_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-shed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-shed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-shed/run' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-shed/index' {
  declare module.exports: $Exports<'babel-plugin-shed'>;
}
declare module 'babel-plugin-shed/index.js' {
  declare module.exports: $Exports<'babel-plugin-shed'>;
}
declare module 'babel-plugin-shed/run.js' {
  declare module.exports: $Exports<'babel-plugin-shed/run'>;
}
