// flow-typed signature: cf94e7e43ff66acabd2a0aec0e7d505b
// flow-typed version: <<STUB>>/modularscale_v^2.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modularscale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'modularscale' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'modularscale/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'modularscale/dist/index.js' {
  declare module.exports: $Exports<'modularscale/dist/index'>;
}
