// flow-typed signature: 7d0725cf8d28e6fa727c90839147fc05
// flow-typed version: <<STUB>>/preload-webpack-plugin_v^1.2.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preload-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'preload-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'preload-webpack-plugin/index' {
  declare module.exports: $Exports<'preload-webpack-plugin'>;
}
declare module 'preload-webpack-plugin/index.js' {
  declare module.exports: $Exports<'preload-webpack-plugin'>;
}
