// flow-typed signature: 4fd5084ddf5519ace557882d4b0e3f86
// flow-typed version: <<STUB>>/react-shed_v^2.8.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-shed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-shed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-shed/lib/index' {
  declare module.exports: any;
}

declare module 'react-shed/umd/react-shed' {
  declare module.exports: any;
}

declare module 'react-shed/umd/react-shed.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-shed/lib/index.js' {
  declare module.exports: $Exports<'react-shed/lib/index'>;
}
declare module 'react-shed/umd/react-shed.js' {
  declare module.exports: $Exports<'react-shed/umd/react-shed'>;
}
declare module 'react-shed/umd/react-shed.min.js' {
  declare module.exports: $Exports<'react-shed/umd/react-shed.min'>;
}
