// flow-typed signature: 32f31674bf9a193eb36fda3a089acb49
// flow-typed version: <<STUB>>/react-media_vvinspee/react-media#d6d66c97378067d5c0907bdb2f9d81b90ff7c9a4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-media'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-media' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-media/es/index' {
  declare module.exports: any;
}

declare module 'react-media/es/Media' {
  declare module.exports: any;
}

declare module 'react-media/karma.conf' {
  declare module.exports: any;
}

declare module 'react-media/Media' {
  declare module.exports: any;
}

declare module 'react-media/modules/__tests__/Media-test' {
  declare module.exports: any;
}

declare module 'react-media/modules/index' {
  declare module.exports: any;
}

declare module 'react-media/modules/Media' {
  declare module.exports: any;
}

declare module 'react-media/tests.webpack' {
  declare module.exports: any;
}

declare module 'react-media/tools/build' {
  declare module.exports: any;
}

declare module 'react-media/tools/es2015-preset' {
  declare module.exports: any;
}

declare module 'react-media/tools/release' {
  declare module.exports: any;
}

declare module 'react-media/umd/react-media' {
  declare module.exports: any;
}

declare module 'react-media/umd/react-media.min' {
  declare module.exports: any;
}

declare module 'react-media/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-media/es/index.js' {
  declare module.exports: $Exports<'react-media/es/index'>;
}
declare module 'react-media/es/Media.js' {
  declare module.exports: $Exports<'react-media/es/Media'>;
}
declare module 'react-media/index' {
  declare module.exports: $Exports<'react-media'>;
}
declare module 'react-media/index.js' {
  declare module.exports: $Exports<'react-media'>;
}
declare module 'react-media/karma.conf.js' {
  declare module.exports: $Exports<'react-media/karma.conf'>;
}
declare module 'react-media/Media.js' {
  declare module.exports: $Exports<'react-media/Media'>;
}
declare module 'react-media/modules/__tests__/Media-test.js' {
  declare module.exports: $Exports<'react-media/modules/__tests__/Media-test'>;
}
declare module 'react-media/modules/index.js' {
  declare module.exports: $Exports<'react-media/modules/index'>;
}
declare module 'react-media/modules/Media.js' {
  declare module.exports: $Exports<'react-media/modules/Media'>;
}
declare module 'react-media/tests.webpack.js' {
  declare module.exports: $Exports<'react-media/tests.webpack'>;
}
declare module 'react-media/tools/build.js' {
  declare module.exports: $Exports<'react-media/tools/build'>;
}
declare module 'react-media/tools/es2015-preset.js' {
  declare module.exports: $Exports<'react-media/tools/es2015-preset'>;
}
declare module 'react-media/tools/release.js' {
  declare module.exports: $Exports<'react-media/tools/release'>;
}
declare module 'react-media/umd/react-media.js' {
  declare module.exports: $Exports<'react-media/umd/react-media'>;
}
declare module 'react-media/umd/react-media.min.js' {
  declare module.exports: $Exports<'react-media/umd/react-media.min'>;
}
declare module 'react-media/webpack.config.js' {
  declare module.exports: $Exports<'react-media/webpack.config'>;
}
