// flow-typed signature: a8d5cd459b38f7115954cca5fd58da6c
// flow-typed version: <<STUB>>/redux-create-reducer_v1.1.x/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-create-reducer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-create-reducer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-create-reducer/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-create-reducer/index' {
  declare module.exports: $Exports<'redux-create-reducer'>;
}
declare module 'redux-create-reducer/index.js' {
  declare module.exports: $Exports<'redux-create-reducer'>;
}
declare module 'redux-create-reducer/test.js' {
  declare module.exports: $Exports<'redux-create-reducer/test'>;
}
