// flow-typed signature: 41bda984f55ace28296afc05155aaa51
// flow-typed version: <<STUB>>/redux-action-types-creator_v1.1.x/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-action-types-creator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-action-types-creator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-action-types-creator/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-action-types-creator/lib/index' {
  declare module.exports: any;
}

declare module 'redux-action-types-creator/src/constants' {
  declare module.exports: any;
}

declare module 'redux-action-types-creator/src/index' {
  declare module.exports: any;
}

declare module 'redux-action-types-creator/tests/createActionType.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-action-types-creator/lib/constants.js' {
  declare module.exports: $Exports<'redux-action-types-creator/lib/constants'>;
}
declare module 'redux-action-types-creator/lib/index.js' {
  declare module.exports: $Exports<'redux-action-types-creator/lib/index'>;
}
declare module 'redux-action-types-creator/src/constants.js' {
  declare module.exports: $Exports<'redux-action-types-creator/src/constants'>;
}
declare module 'redux-action-types-creator/src/index.js' {
  declare module.exports: $Exports<'redux-action-types-creator/src/index'>;
}
declare module 'redux-action-types-creator/tests/createActionType.spec.js' {
  declare module.exports: $Exports<'redux-action-types-creator/tests/createActionType.spec'>;
}
